// <auto-generated />
namespace Http.File.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v20211125 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v20211125));
        
        string IMigrationMetadata.Id
        {
            get { return "202111250849413_v20211125"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
